### ISSUE TITLE
about Microbit V2

### ISSUE THREAD

**Issue by YzmsLinq** [rhubarbdog/microbit-dht11#1] opened 2021-06-21 08:55 UTC
It doesn't work normally in microbit V2, and it can't read data all the time

**Comment by rhubarbdog** [comment] 2021-06-29 12:18
Yes the problem is the cpu on the v2 is 64mhz where as on v1 it only 16mhz. I don't have much tech at the moment so won't be fixing this for a while

**Comment by YzmsLinq** [comment] 2021-06-30 10:33
Thank you for your reply, and hope to resolve this issue as soon as possible.

**Comment by MeqdadDev** [comment] 2022-06-23 09:39
Hello guys,
Any updates about working with micro:bit v2 with DHT11?

Thanks for your efforts.

**Comment by MeqdadDev** [comment] 2022-06-23 09:42
Hi dears,

For those who are working with some hardware sensors and modules with micro:bit v2, I would like to recommend this repo for you: [BBC micro:bit with MicroPython](https://github.com/MeqdadDev/microbit-micropython-samples)
Where I modularized and prepared some micro:bit projects using MicroPython.

**Comment by rhubarbdog** [comment] 2022-10-01 17:15
hi the new code is done tested and available to clone and use. use the correct code for the microbit you have

**Closed as completed by rhubarbdog** 2022-10-01 17:15 UTC
